"""Locked public identifiers and protocol defaults for the Agents AI API."""

from __future__ import annotations

from app.apps_catalog.agent_product import (
    AGENTS_AI_APP_SLUG,
    AGENT_REQUESTS_DAILY_ENTITLEMENT,
    AGENT_REQUESTS_USAGE_METRIC,
)
from app.common.public_model import PUBLIC_MODEL_ID

PUBLIC_AGENT_MODEL_IDS: frozenset[str] = frozenset({PUBLIC_MODEL_ID})
PUBLIC_AGENT_MODEL_CREATED = 1_770_000_000
PUBLIC_AGENT_MODEL_OWNER = "geem"

DEFAULT_AGENT_MAX_MESSAGES = 64
DEFAULT_AGENT_MAX_BODY_BYTES = 262_144
DEFAULT_AGENT_MAX_TOOLS = 32
DEFAULT_AGENT_TOOL_RESULT_MAX_CHARS = 8_000
DEFAULT_AGENT_TOOL_SCHEMA_MAX_BYTES = 65_536
DEFAULT_AGENT_CLIENT_INSTRUCTIONS_MAX_CHARS = 4_000
DEFAULT_AGENT_CONTEXT_CACHE_TTL_SECONDS = 900
DEFAULT_AGENT_MAX_OUTPUT_TOKENS = 4_096

TOOL_NAME_PATTERN = r"^[A-Za-z0-9_-]{1,64}$"
SUPPORTED_AGENT_FINISH_REASONS: frozenset[str] = frozenset(
    {"stop", "tool_calls", "length", "content_filter"}
)

CLIENT_INSTRUCTIONS_TAG = "CLIENT_AGENT_INSTRUCTIONS"
CLIENT_TOOL_RESULT_TAG = "CLIENT_TOOL_RESULT"

__all__ = [
    "AGENTS_AI_APP_SLUG",
    "AGENT_REQUESTS_DAILY_ENTITLEMENT",
    "AGENT_REQUESTS_USAGE_METRIC",
    "CLIENT_INSTRUCTIONS_TAG",
    "CLIENT_TOOL_RESULT_TAG",
    "DEFAULT_AGENT_CLIENT_INSTRUCTIONS_MAX_CHARS",
    "DEFAULT_AGENT_CONTEXT_CACHE_TTL_SECONDS",
    "DEFAULT_AGENT_MAX_BODY_BYTES",
    "DEFAULT_AGENT_MAX_MESSAGES",
    "DEFAULT_AGENT_MAX_OUTPUT_TOKENS",
    "DEFAULT_AGENT_MAX_TOOLS",
    "DEFAULT_AGENT_TOOL_RESULT_MAX_CHARS",
    "DEFAULT_AGENT_TOOL_SCHEMA_MAX_BYTES",
    "PUBLIC_AGENT_MODEL_CREATED",
    "PUBLIC_AGENT_MODEL_IDS",
    "PUBLIC_AGENT_MODEL_OWNER",
    "SUPPORTED_AGENT_FINISH_REASONS",
    "TOOL_NAME_PATTERN",
]
