import 'package:flutter/widgets.dart';

class AppStrings {
  const AppStrings(this.languageCode);

  factory AppStrings.of(BuildContext context) =>
      AppStrings(Localizations.localeOf(context).languageCode);

  final String languageCode;

  bool get isArabic => languageCode == 'ar';

  String text(String key) =>
      (_values[languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  String error(String? code, [String? fallback]) {
    final key = switch (code) {
      'invalid_credentials' => 'errorInvalidCredentials',
      'email_not_verified' => 'errorEmailNotVerified',
      'invalid_verification_token' => 'errorInvalidVerification',
      'verification_token_expired' => 'errorExpiredVerification',
      'invalid_reset_token' => 'errorInvalidReset',
      'reset_token_expired' => 'errorExpiredReset',
      'session_expired' ||
      'session_revoked' ||
      'unauthorized' => 'errorSessionExpired',
      'forbidden' || 'insufficient_workspace_role' => 'errorForbidden',
      'rate_limited' => 'errorRateLimited',
      'monthly_quota_exceeded' || 'credit_balance_exhausted' => 'errorQuota',
      'network' => 'errorNetwork',
      'validation' => 'errorValidation',
      'expert_required' => 'expertRequired',
      'server_error' => 'errorServer',
      _ => null,
    };
    if (key != null) return text(key);
    return fallback?.trim().isNotEmpty == true
        ? fallback!
        : text('errorGeneric');
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appName': 'Geem',
      'loginTitle': 'Welcome back',
      'loginSubtitle': 'Sign in to continue to your workspace chats.',
      'email': 'Email address',
      'emailHint': 'name@company.com',
      'password': 'Password',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign in',
      'signingIn': 'Signing in…',
      'forgotTitle': 'Reset your password',
      'forgotSubtitle': 'Enter your email and we’ll send a secure reset link.',
      'sendResetLink': 'Send reset link',
      'sending': 'Sending…',
      'forgotSuccessTitle': 'Check your inbox',
      'forgotSuccessBody':
          'If an account exists for that email, a reset link is on its way.',
      'useResetLink': 'Use a reset link',
      'backToSignIn': 'Back to sign in',
      'checkEmailTitle': 'Confirm your email',
      'checkEmailKnown': 'We sent a verification link to',
      'checkEmailSubtitle':
          'Open the link in your email to activate your account.',
      'resendVerification': 'Resend verification email',
      'resending': 'Resending…',
      'verificationResent': 'A new verification email has been sent.',
      'haveVerificationLink': 'Paste verification link',
      'verificationLink': 'Verification link or token',
      'verifyNow': 'Verify email',
      'verifyTitle': 'Verifying your email',
      'verifyWorking': 'Please wait while Geem confirms your email.',
      'resetTitle': 'Choose a new password',
      'resetSubtitle':
          'Paste the reset link if it was not opened directly in Geem.',
      'resetLink': 'Reset link or token',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm password',
      'passwordHint': 'Use at least 8 characters.',
      'resetPassword': 'Reset password',
      'resetting': 'Resetting…',
      'passwordMismatch': 'The passwords do not match.',
      'requiredFields': 'Please complete all required fields.',
      'invalidEmail': 'Enter a valid email address.',
      'language': 'العربية',
      'newChat': 'New chat',
      'workspaces': 'Workspaces',
      'workspace': 'Workspace',
      'favorites': 'Favorites',
      'pinned': 'Pinned',
      'recent': 'Recent',
      'noFavorites': 'No favorite chats yet',
      'noPinned': 'No pinned chats yet',
      'noConversations': 'Your latest chats will appear here',
      'untitled': 'New conversation',
      'logout': 'Sign out',
      'profile': 'Profile',
      'account': 'Account',
      'currentWorkspace': 'Current workspace',
      'role': 'Role',
      'preferences': 'Preferences',
      'languageSetting': 'Language',
      'logoutConfirmTitle': 'Log out?',
      'logoutConfirmBody':
          'You will need to sign in again to access this workspace.',
      'loggingOut': 'Logging out…',
      'starterTitle': 'How can Geem help?',
      'starterSubtitle': 'Choose an expert and start a focused conversation.',
      'starterDisclaimer':
          'Geem can make mistakes. Check important information.',
      'selectExpert': 'Choose expert',
      'expertRequired': 'Choose an available expert before sending.',
      'askHint': 'Ask {{name}} anything…',
      'messageHint': 'Message Geem…',
      'send': 'Send',
      'sendingMessage': 'Starting chat…',
      'stop': 'Stop',
      'jumpToLatest': 'Jump to latest',
      'thinking': 'Geem is thinking…',
      'thinkingCheckingSources': 'Checking sources…',
      'thinkingGatheringContext': 'Gathering context…',
      'thinkingReadingKnowledge': 'Reading your knowledge…',
      'thinkingPreparingAnswer': 'Preparing an answer…',
      'thinkingLookingUp': 'Looking that up…',
      'retrieving': 'Searching sources…',
      'generating': 'Writing an answer…',
      'retrying': 'Trying again…',
      'retry': 'Try again',
      'sources': 'Sources',
      'page': 'Page',
      'chatUnavailable': 'Chat is not available in this workspace.',
      'noWorkspacesTitle': 'No workspace access',
      'noWorkspacesBody':
          'Ask a workspace owner to invite you, then sign in again.',
      'reload': 'Reload',
      'conversationActions': 'Conversation actions',
      'addFavorite': 'Add to favorites',
      'removeFavorite': 'Remove from favorites',
      'pin': 'Pin',
      'unpin': 'Unpin',
      'rename': 'Rename',
      'delete': 'Delete',
      'renameChat': 'Rename chat',
      'deleteChat': 'Delete chat?',
      'deleteChatBody': 'This conversation will be removed from your history.',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'errorInvalidCredentials': 'The email or password is incorrect.',
      'errorEmailNotVerified': 'Confirm your email before signing in.',
      'errorInvalidVerification': 'This verification link is invalid.',
      'errorExpiredVerification':
          'This verification link has expired. Request a new one.',
      'errorInvalidReset': 'This password reset link is invalid.',
      'errorExpiredReset': 'This password reset link has expired.',
      'errorSessionExpired': 'Your session expired. Please sign in again.',
      'errorForbidden': 'You do not have permission to do that.',
      'errorRateLimited': 'Too many attempts. Please wait and try again.',
      'errorQuota': 'This workspace has reached its AI usage limit.',
      'errorNetwork':
          'Could not reach Geem. Check your connection and try again.',
      'errorValidation': 'Check the entered information and try again.',
      'errorServer': 'Geem is temporarily unavailable. Please try again.',
      'errorGeneric': 'Something went wrong. Please try again.',
    },
    'ar': {
      'appName': 'جيم',
      'loginTitle': 'مرحبًا بعودتك',
      'loginSubtitle': 'سجّل الدخول للمتابعة إلى محادثات مساحة العمل.',
      'email': 'البريد الإلكتروني',
      'emailHint': 'name@company.com',
      'password': 'كلمة المرور',
      'showPassword': 'إظهار كلمة المرور',
      'hidePassword': 'إخفاء كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'signingIn': 'جارٍ تسجيل الدخول…',
      'forgotTitle': 'إعادة تعيين كلمة المرور',
      'forgotSubtitle': 'أدخل بريدك وسنرسل لك رابطًا آمنًا لإعادة التعيين.',
      'sendResetLink': 'إرسال رابط التعيين',
      'sending': 'جارٍ الإرسال…',
      'forgotSuccessTitle': 'تحقق من بريدك',
      'forgotSuccessBody':
          'إذا كان الحساب موجودًا فسيصلك رابط إعادة التعيين قريبًا.',
      'useResetLink': 'استخدام رابط التعيين',
      'backToSignIn': 'العودة لتسجيل الدخول',
      'checkEmailTitle': 'تأكيد بريدك الإلكتروني',
      'checkEmailKnown': 'أرسلنا رابط التحقق إلى',
      'checkEmailSubtitle': 'افتح الرابط في بريدك لتفعيل حسابك.',
      'resendVerification': 'إعادة إرسال رسالة التحقق',
      'resending': 'جارٍ إعادة الإرسال…',
      'verificationResent': 'تم إرسال رسالة تحقق جديدة.',
      'haveVerificationLink': 'لصق رابط التحقق',
      'verificationLink': 'رابط أو رمز التحقق',
      'verifyNow': 'تأكيد البريد',
      'verifyTitle': 'جارٍ تأكيد بريدك',
      'verifyWorking': 'يرجى الانتظار بينما يؤكد جيم بريدك الإلكتروني.',
      'resetTitle': 'اختر كلمة مرور جديدة',
      'resetSubtitle': 'الصق رابط التعيين إذا لم يُفتح داخل جيم مباشرة.',
      'resetLink': 'رابط أو رمز إعادة التعيين',
      'newPassword': 'كلمة المرور الجديدة',
      'confirmPassword': 'تأكيد كلمة المرور',
      'passwordHint': 'استخدم 8 أحرف على الأقل.',
      'resetPassword': 'تعيين كلمة المرور',
      'resetting': 'جارٍ التعيين…',
      'passwordMismatch': 'كلمتا المرور غير متطابقتين.',
      'requiredFields': 'يرجى إكمال جميع الحقول المطلوبة.',
      'invalidEmail': 'أدخل بريدًا إلكترونيًا صحيحًا.',
      'language': 'English',
      'newChat': 'محادثة جديدة',
      'workspaces': 'مساحات العمل',
      'workspace': 'مساحة العمل',
      'favorites': 'المفضلة',
      'pinned': 'المثبتة',
      'recent': 'الأخيرة',
      'noFavorites': 'لا توجد محادثات مفضلة بعد',
      'noPinned': 'لا توجد محادثات مثبتة بعد',
      'noConversations': 'ستظهر أحدث محادثاتك هنا',
      'untitled': 'محادثة جديدة',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'account': 'الحساب',
      'currentWorkspace': 'مساحة العمل الحالية',
      'role': 'الدور',
      'preferences': 'التفضيلات',
      'languageSetting': 'اللغة',
      'logoutConfirmTitle': 'تسجيل الخروج؟',
      'logoutConfirmBody':
          'ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى مساحة العمل هذه.',
      'loggingOut': 'جارٍ تسجيل الخروج…',
      'starterTitle': 'كيف يمكن لجيم مساعدتك؟',
      'starterSubtitle': 'اختر خبيرًا وابدأ محادثة مركّزة.',
      'starterDisclaimer': 'قد يخطئ جيم. تحقق من المعلومات المهمة.',
      'selectExpert': 'اختر الخبير',
      'expertRequired': 'اختر خبيرًا متاحًا قبل الإرسال.',
      'askHint': 'اسأل {{name}} أي شيء…',
      'messageHint': 'اكتب رسالتك إلى جيم…',
      'send': 'إرسال',
      'sendingMessage': 'جارٍ بدء المحادثة…',
      'stop': 'إيقاف',
      'jumpToLatest': 'الانتقال إلى الأحدث',
      'thinking': 'Geem يفكر…',
      'thinkingCheckingSources': 'جارٍ التحقق من المصادر…',
      'thinkingGatheringContext': 'جارٍ جمع السياق…',
      'thinkingReadingKnowledge': 'جارٍ قراءة معرفتك…',
      'thinkingPreparingAnswer': 'جارٍ تجهيز الإجابة…',
      'thinkingLookingUp': 'جارٍ البحث عن المعلومة…',
      'retrieving': 'جارٍ البحث في المصادر…',
      'generating': 'جارٍ كتابة الإجابة…',
      'retrying': 'جارٍ المحاولة مرة أخرى…',
      'retry': 'إعادة المحاولة',
      'sources': 'المصادر',
      'page': 'صفحة',
      'chatUnavailable': 'المحادثة غير متاحة في مساحة العمل هذه.',
      'noWorkspacesTitle': 'لا توجد مساحة عمل',
      'noWorkspacesBody':
          'اطلب من مالك مساحة العمل دعوتك، ثم سجّل الدخول مجددًا.',
      'reload': 'إعادة التحميل',
      'conversationActions': 'إجراءات المحادثة',
      'addFavorite': 'إضافة إلى المفضلة',
      'removeFavorite': 'إزالة من المفضلة',
      'pin': 'تثبيت',
      'unpin': 'إلغاء التثبيت',
      'rename': 'إعادة التسمية',
      'delete': 'حذف',
      'renameChat': 'إعادة تسمية المحادثة',
      'deleteChat': 'حذف المحادثة؟',
      'deleteChatBody': 'ستُزال هذه المحادثة من سجلك.',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'close': 'إغلاق',
      'errorInvalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'errorEmailNotVerified': 'أكد بريدك الإلكتروني قبل تسجيل الدخول.',
      'errorInvalidVerification': 'رابط التحقق غير صالح.',
      'errorExpiredVerification':
          'انتهت صلاحية رابط التحقق. اطلب رابطًا جديدًا.',
      'errorInvalidReset': 'رابط إعادة تعيين كلمة المرور غير صالح.',
      'errorExpiredReset': 'انتهت صلاحية رابط إعادة تعيين كلمة المرور.',
      'errorSessionExpired': 'انتهت جلستك. يرجى تسجيل الدخول مجددًا.',
      'errorForbidden': 'ليست لديك صلاحية لتنفيذ هذا الإجراء.',
      'errorRateLimited': 'محاولات كثيرة. انتظر قليلًا ثم حاول مجددًا.',
      'errorQuota': 'وصلت مساحة العمل إلى حد استخدام الذكاء الاصطناعي.',
      'errorNetwork': 'تعذر الاتصال بجيم. تحقق من الشبكة وحاول مجددًا.',
      'errorValidation': 'تحقق من البيانات المدخلة وحاول مجددًا.',
      'errorServer': 'جيم غير متاح مؤقتًا. حاول لاحقًا.',
      'errorGeneric': 'حدث خطأ ما. يرجى المحاولة مجددًا.',
    },
  };
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
